from . import (
    msv, javelin, opentrack, circuit_days, silverstone, rma,
    mot, nolimits, goldtrack, msevents, goodwood,
    slipandgrip, trackobsession,
    rsr_nurburg, gedlich, trackdays_events,
    pembrey, llandow, kirkistown,
    trackday_solutions,
)

SCRAPERS = {
    "msv": msv,
    "javelin": javelin,
    "opentrack": opentrack,
    "circuit_days": circuit_days,
    "silverstone": silverstone,
    "rma": rma,
    "mot": mot,
    "nolimits": nolimits,
    "goldtrack": goldtrack,
    "msevents": msevents,
    "goodwood": goodwood,
    "slipandgrip": slipandgrip,
    "trackobsession": trackobsession,
    "rsr_nurburg": rsr_nurburg,
    "gedlich": gedlich,
    "trackdays_events": trackdays_events,
    "pembrey": pembrey,
    "llandow": llandow,
    "kirkistown": kirkistown,
    "trackday_solutions": trackday_solutions,
}

# Display names — for the UI Source filter dropdown and the events table.
ORGANISER_DISPLAY = {
    "msv": "MSV Trackdays",
    "javelin": "Javelin Trackdays",
    "opentrack": "OpenTrack",
    "circuit_days": "Circuit Days",
    "silverstone": "Silverstone",
    "rma": "RMA Track Days",
    "mot": "MOT Trackdays",
    "nolimits": "No Limits Trackdays",
    "goldtrack": "Goldtrack",
    "msevents": "Motorsport Events",
    "goodwood": "Goodwood Motor Circuit",
    "slipandgrip": "Slip and Grip Automotive",
    "trackobsession": "Track Obsession",
    "rsr_nurburg": "RSRNurburg (Europe)",
    "gedlich": "GEDLICH Racing",
    "trackdays_events": "Trackdays.events (aggregator)",
    "nurburgring_tf": "Nürburgring (Touristenfahrten)",
    "pembrey": "Pembrey Circuit",
    "llandow": "Llandow Circuit",
    "kirkistown": "Kirkistown Racing Circuit",
    "trackday_solutions": "Trackday Solutions",
}

# Region grouping for the dropdown (UK first, EU after).
SOURCE_REGION = {
    "msv": "UK", "javelin": "UK", "opentrack": "UK", "circuit_days": "UK",
    "silverstone": "UK", "rma": "UK", "mot": "UK", "nolimits": "UK",
    "goldtrack": "UK", "msevents": "UK", "goodwood": "UK",
    "slipandgrip": "UK", "trackobsession": "UK",
    "rsr_nurburg": "EU",
    "gedlich": "EU",
    "trackdays_events": "EU",
    "nurburgring_tf": "EU",
    "pembrey": "UK",
    "llandow": "UK",
    "trackday_solutions": "UK",
    "kirkistown": "UK",
}
