"""Lat/Lng coordinates for circuits used by the interactive map.

Keys must exactly match the canonical circuit names produced by
normalise.canonical_circuit() so the map page can match DB rows to markers.
Anything not listed here just won't appear as a marker (the table still does).
"""

# Circuits we know run public trackdays but we can't reliably scrape — the map
# treats these as "active but external": red marker with a "?" count and a
# popup that sends users straight to the circuit's own booking page.
EXTERNAL_CIRCUITS: set[str] = {
    # Known active trackday venues with no scrapeable public calendar.
    # Add more as we encounter them; popup sends users to CIRCUIT_WEBSITES[name].
    "Mondello Park",     # Checkfront widget per discipline; can't reliably scrape
    "Bishopscourt",      # NI bike circuit, runs days via clubs, no public feed
}

CIRCUIT_COORDS: dict[str, tuple[float, float]] = {
    # ===== UK =====
    "Silverstone":          (52.0717, -1.0167),
    "Donington Park":       (52.8306, -1.3753),
    "Brands Hatch":         (51.3589,  0.2603),
    "Snetterton":           (52.4658,  0.9489),
    "Oulton Park":          (53.1789, -2.6149),
    "Cadwell Park":         (53.3115, -0.0517),
    "Castle Combe":         (51.4925, -2.2150),
    "Anglesey":             (53.1937, -4.5095),
    "Bedford Autodrome":    (52.2244, -0.4651),
    "Thruxton":             (51.2122, -1.6028),
    "Croft":                (54.4564, -1.5589),
    "Knockhill":            (56.1297, -3.5128),
    "Pembrey":              (51.6736, -4.2811),
    "Blyton Park":          (53.4564, -0.7050),
    "Rockingham":           (52.5917, -0.6536),
    "Mallory Park":         (52.6019, -1.3408),
    "Lydden Hill":          (51.1631,  1.2411),
    "Goodwood":             (50.8597, -0.7565),
    "Llandow":              (51.4500, -3.4533),
    "Curborough":           (52.7397, -1.7686),

    # ===== Europe =====
    "Spa-Francorchamps":              (50.4372,  5.9714),
    "Nürburgring":                     (50.3356,  6.9475),
    "Nürburgring (Nordschleife)":      (50.3356,  6.9475),
    "Zandvoort":                       (52.3886,  4.5408),
    "Hockenheim":                      (49.3289,  8.5658),
    "Magny-Cours":                     (46.8631,  3.1631),
    "Imola":                           (44.3439, 11.7167),
    "Mugello":                         (43.9975, 11.3717),
    "Le Mans (Bugatti)":               (47.9569,  0.2078),
    "Paul Ricard":                     (43.2497,  5.7917),
    "Portimão":                        (37.2289, -8.6275),
    "Estoril":                         (38.7506, -9.3947),
    "Barcelona-Catalunya":             (41.5700,  2.2611),
    "Monza":                           (45.6156,  9.2808),
    "TT Circuit Assen":                (52.9594,  6.5217),
    "Valencia (Ricardo Tormo)":        (39.4858, -0.6294),
    "Jerez":                           (36.7086, -6.0344),
    "Circuito de Navarra":             (42.5867, -2.0939),
    # Common Trackdays.events European circuits
    "Most":                            (50.5172, 13.6064),
    "Autodrom Most":                   (50.5172, 13.6064),
    "Brno":                            (49.2050, 16.4444),
    "Automotodrom Brno":               (49.2050, 16.4444),
    "Pannonia Ring":                   (47.3158, 16.5306),
    "Slovakia Ring":                   (48.0500, 17.4733),
    "Sachsenring":                     (50.7906, 12.6864),
    "Oschersleben":                    (52.0269, 11.2792),
    "Motorsport Arena Oschersleben":   (52.0269, 11.2792),
    "Dijon-Prenois":                   (47.3658,  4.8961),
    "Anneau du Rhin":                  (47.8500,  7.4136),
    "Croix-en-Ternois":                (50.4258,  2.2706),
    "Mas du Clos":                     (45.9667,  2.1667),
    "Mirecourt":                       (48.3000,  6.1500),
    "Lédenon":                         (43.9000,  4.5036),
    "Pôle Mécanique Alès Cévennes":    (44.1167,  4.0667),
    "Bresse":                          (46.5000,  5.2667),
    "Circuit de Bresse":               (46.5000,  5.2667),
    "Circuit Bugatti (Le Mans)":       (47.9569,  0.2078),
    "Lausitzring":                     (51.5345, 13.9244),
    "Schleizer Dreieck":               (50.5733, 11.8278),
    "Race Park Meppen":                (52.7100,  7.2900),
    "Salzburgring":                    (47.8253, 13.1750),
    "A1 Motor Park":                   (37.7775, 30.5658),
    "Grobnik Circuit | Rijeka":        (45.3697, 14.5039),
    "Bikernieki Racetrack":            (56.9569, 24.2294),
    "Misano World Circuit":            (43.9617, 12.6831),
    "Mugello Circuit":                 (43.9975, 11.3717),
    "Cremona Circuit":                 (45.0578,  9.9706),
    "Circuito Tazio Nuvolari":         (45.1611,  9.4117),
    "Balaton Park Circuit":            (47.0381, 17.7842),
    "Almeria (Iberia Circuit)":        (37.0386, -2.3650),
    "Porsche Ring":                    (51.4317, 12.2986),
    "Circuit Jules Tacheny Mettet":    (50.3214,  4.6708),
    "Circuit des Ecuyers":             (49.0150,  3.4150),
    "Circuit Paul Ricard":             (43.2497,  5.7917),
    "Hungaroring":                     (47.5828, 19.2486),
    "Red Bull Ring":                   (47.2197, 14.7647),
    "Autodromo di Vairano":            (45.3528,  9.4358),
    "Circuit Bilster Berg":            (51.7553,  9.0150),
    "Bilster Berg":                    (51.7553,  9.0150),
    "Hungaroring":                     (47.5828, 19.2486),

    # Added from DB audit (May 2026):
    "Red Bull Ring / Spielberg":               (47.2197, 14.7647),
    "Vaison Piste":                            (44.2367,  5.0775),
    "Anneau-du-Rhin":                          (47.8500,  7.4136),
    "Mettet":                                  (50.3214,  4.6708),
    "Zolder":                                  (50.9892,  5.2581),
    "Fay de Bretagne":                         (47.4017, -1.7367),
    "Tazio Nuvolari Circuit":                  (45.1611,  9.4117),
    "Le Luc (circuit du Var)":                 (43.3878,  6.3878),
    "Clastres":                                (49.7531,  3.2336),
    "Pau Arnos":                               (43.4131, -0.4358),
    "Franciacorta":                            (45.5872,  9.9928),
    "Boxberg":                                 (49.4892,  9.6603),
    "Aragon Motorland":                        (41.0556, -0.2167),
    "Val de Vienne / Le Vigeant":              (46.1844,  0.6925),
    "Alès":                                    (44.1167,  4.0667),
    "Misano":                                  (43.9617, 12.6831),
    "Issoire":                                 (45.5364,  3.2575),
    "Fontenay-le-Comte (circuits de Vendée)":  (46.4667, -0.7889),
    "Oschersleben Motorsport Arena":           (52.0269, 11.2792),
    "Charade":                                 (45.7464,  3.0167),
    "Les Ecuyers":                             (49.0150,  3.4150),
    "Chenevières":                             (48.5394,  6.6300),
    "Gross Dölln":                             (53.0900, 13.7600),
    "Abingdon":                                (51.6919, -1.3158),
    "Lurcy-Levis":                             (46.7194,  2.9558),
    "Nogaro":                                  (43.7611, -0.0494),
    "Meppen Racepark":                         (52.7100,  7.2900),
    "Mireval":                                 (43.5036,  3.7950),
    "Ladoux":                                  (45.8508,  3.1133),
    "Vairano":                                 (45.3528,  9.4358),
    "Balocco":                                 (45.4769,  8.3939),
    "Chambley":                                (49.0317,  5.8717),
    "Guadix (Granada)":                        (37.3133, -3.1300),
    "Circuits de l'Ouest Parisien (Dreux)":    (48.7236,  1.3825),
    "Most Autodrom":                           (50.5172, 13.6064),
    "Monteblanco":                             (37.4083, -6.4892),
    "Slovakiaring":                            (48.0500, 17.4733),
    "Vallelunga":                              (42.1592, 12.3744),
    # Keevil airfield trackday venue (UK)
    "Keevil":                                  (51.3392, -2.1175),

    # Ireland
    "Mondello Park":                           (53.2569, -6.7500),
    "Kirkistown":                              (54.4581, -5.4503),
    "Bishopscourt":                            (54.3322, -5.5731),
}


# Official circuit websites — used for the "Visit circuit" link on grey
# (inactive) map markers, so users always have somewhere to go even when we
# don't currently list any events. Add as we know them.
CIRCUIT_WEBSITES: dict[str, str] = {
    # ===== UK & Ireland =====
    "Silverstone":                  "https://www.silverstone.co.uk/",
    "Donington Park":               "https://www.donington-park.co.uk/",
    "Brands Hatch":                 "https://www.brandshatch.co.uk/",
    "Snetterton":                   "https://www.snetterton.co.uk/",
    "Oulton Park":                  "https://www.oultonpark.co.uk/",
    "Cadwell Park":                 "https://www.cadwellpark.co.uk/",
    "Castle Combe":                 "https://www.castlecombecircuit.co.uk/",
    "Anglesey":                     "https://www.angleseycircuit.com/",
    "Bedford Autodrome":            "https://www.bedfordautodrome.com/",
    "Thruxton":                     "https://thruxtonracing.co.uk/",
    "Croft":                        "https://www.croftcircuit.co.uk/",
    "Knockhill":                    "https://www.knockhill.com/",
    "Pembrey":                      "https://pembreycircuit.co.uk/",
    "Blyton Park":                  "https://www.blytonpark.co.uk/",
    "Mallory Park":                 "https://www.mallorypark.co.uk/",
    "Lydden Hill":                  "https://www.lyddenhill.co.uk/",
    "Goodwood":                     "https://www.goodwood.com/motorsport/motor-circuit/",
    "Llandow":                      "https://www.llandow.com/",
    "Curborough":                   "https://www.curborough.co.uk/",
    "Rockingham":                   "https://en.wikipedia.org/wiki/Rockingham_Motor_Speedway",
    "Mondello Park":                "https://mondellopark.ie/",
    "Kirkistown":                   "https://kirkistown.com/",
    "Bishopscourt":                 "https://www.bishopscourtracingcircuit.com/",

    # ===== Europe =====
    "Spa-Francorchamps":            "https://www.spa-francorchamps.be/",
    "Nürburgring":                  "https://www.nuerburgring.de/",
    "Nürburgring (Nordschleife)":   "https://www.nuerburgring.de/driving/touristdrives",
    "Zandvoort":                    "https://www.circuitzandvoort.nl/",
    "Hockenheim":                   "https://www.hockenheimring.de/",
    "Magny-Cours":                  "https://www.circuitmagnycours.com/",
    "Imola":                        "https://www.autodromoimola.it/",
    "Mugello":                      "https://www.mugellocircuit.com/",
    "Mugello Circuit":              "https://www.mugellocircuit.com/",
    "Le Mans (Bugatti)":            "https://www.lemans.org/",
    "Circuit Bugatti (Le Mans)":    "https://www.lemans.org/",
    "Paul Ricard":                  "https://www.circuitpaulricard.com/",
    "Circuit Paul Ricard":          "https://www.circuitpaulricard.com/",
    "Portimão":                     "https://www.autodromodoalgarve.com/",
    "Estoril":                      "https://www.circuito-estoril.pt/",
    "Barcelona-Catalunya":          "https://www.circuitcat.com/",
    "Monza":                        "https://www.monzanet.it/",
    "TT Circuit Assen":             "https://www.ttcircuit.com/",
    "Valencia (Ricardo Tormo)":     "https://www.circuitvalencia.com/",
    "Jerez":                        "https://www.circuitodejerez.com/",
    "Circuito de Navarra":          "https://www.circuitodenavarra.com/",
    "Most":                         "https://www.autodrom-most.cz/",
    "Autodrom Most":                "https://www.autodrom-most.cz/",
    "Brno":                         "https://www.automotodrombrno.cz/",
    "Automotodrom Brno":            "https://www.automotodrombrno.cz/",
    "Pannonia Ring":                "https://www.pannoniaring.hu/",
    "Slovakia Ring":                "https://www.slovakiaring.sk/",
    "Slovakiaring":                 "https://www.slovakiaring.sk/",
    "Sachsenring":                  "https://www.sachsenring-circuit.com/",
    "Oschersleben":                 "https://www.motorsportarena.com/",
    "Motorsport Arena Oschersleben":"https://www.motorsportarena.com/",
    "Oschersleben Motorsport Arena":"https://www.motorsportarena.com/",
    "Dijon-Prenois":                "https://www.circuit-dijon-prenois.com/",
    "Anneau du Rhin":               "https://www.anneau-du-rhin.com/",
    "Anneau-du-Rhin":               "https://www.anneau-du-rhin.com/",
    "Lausitzring":                  "https://www.dekra-lausitzring.com/",
    "Salzburgring":                 "https://www.salzburgring.com/",
    "Misano World Circuit":         "https://www.misanocircuit.com/",
    "Misano":                       "https://www.misanocircuit.com/",
    "Hungaroring":                  "https://www.hungaroring.hu/",
    "Red Bull Ring":                "https://www.projekt-spielberg.com/",
    "Red Bull Ring / Spielberg":    "https://www.projekt-spielberg.com/",
    "Vallelunga":                   "https://www.acivallelunga.it/",
    "Bilster Berg":                 "https://www.bilster-berg.de/",
    "Circuit Bilster Berg":         "https://www.bilster-berg.de/",
    "Cremona Circuit":              "https://www.cremonacircuit.it/",
    "Franciacorta":                 "https://www.franciacortacircuit.it/",
    "Aragon Motorland":             "https://www.motorlandaragon.com/",
    "Pau Arnos":                    "https://www.circuit-pau-arnos.com/",
    "Nogaro":                       "https://www.circuit-nogaro.com/",
    "Charade":                      "https://www.charade.fr/",
    "Le Luc (circuit du Var)":      "https://www.circuitduvar.com/",
    "Mettet":                       "https://www.circuit-mettet.be/",
    "Circuit Jules Tacheny Mettet": "https://www.circuit-mettet.be/",
    "Zolder":                       "https://www.circuit-zolder.be/",
}


